export const breadcrumbMap = {
  dashboard: "Dashboard",
  contratos: "Contratos",
  "contratos/novo-contrato": "Novo Contrato",
  "contratos/editar-contrato": "Editar Contrato",
  "contratos/historico": "Histórico de Contratos",
  historico: "Histórico",
  "contratos/historico/visualizar-contrato": "Visualizar Contrato",
  clientes: "Clientes",
  "cliente-cadastrar": "Cadastrar Cliente",
  "cliente-editar": "Editar Cliente",
  "visualizar-cliente": "Visualizar Cliente",
  execucao: "Execução",
  "execucao/historico": "Histórico de Execução",
  "execucao/enviar-contratos": "Enviar Contratos",
  admin: "Administração",
  "admin/usuarios": "Usuários",
  "admin/permissoes": "Permissões",
  "minha-conta": "Minha Conta",
  login: "Login",
  logout: "Logout",
};
